name: adep_env
channels:
    - conda-forge
dependencies:
    - python=3.8
    - rapidsai::cuml=22.02
    - rapidsai::cudf=22.02
    - nvidia::cudatoolkit=11.5
    - anaconda::ipykernel
    - conda-forge::nbformat
    - plotly::plotly
    - anaconda::graphviz
    - conda-forge::panel
    - anaconda::ipywidgets
    - conda-forge::jupyter-dash
    - conda-forge::dash-daq
    - conda-forge::dash-html-components
    - conda-forge::dash-core-components
    - conda-forge::dask-cuda
    - conda-forge::numpy<1.23
